name: Move after merge
on: 
  pull_request:
    branches:
      - main
    types: [closed]          
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:  
  # First job called "move_card"
  move_card:
    if: ${{ github.event.pull_request.merged == true }}
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout repo
        uses: actions/checkout@v2
      # Runs a Python script
      - name: Moving card out of TESTING
        run: python .github/workflows/cards.py --merged
        env:
          # Branch name
          BRANCH: ${{ github.head_ref }}
          # Github Access Token
          GITHUB_TOKEN: ${{ github.token }}
          # Repository owner & repository name
          REPO: ${{ github.repository }}
